show:
	aws secretsmanager get-secret-value --secret-id my-username
	aws secretsmanager get-secret-value --secret-id my-password
	aws secretsmanager get-secret-value --secret-id my-json-credential

show-pokedex:
	aws secretsmanager get-secret-value --secret-id my-best-pokemon
