apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: amiable-nirvana-263914
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: us-central1-c
          # name of the GKE cluster
          clusterName: cluster-1
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: amiable-nirvana-263914
          # reference the sa from above
          serviceAccountRef:
            name: external-secrets
            namespace: eso

