apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-example
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store               # name of the SecretStore (or kind specified)
  target:
    name: secret-create-in-the-cluster # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: test-secret
    remoteRef:
      key: test-secret
  # dataFrom:
  # - extract:
  #     key: test-secret

