apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example # Customisable
  namespace: default # Same of the SecretStores
spec:
  refreshInterval: 1h # Refresh interval for which push secret will reconcile
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: gcp-store-write               # name of the SecretStore (or kind specified)
  selector:
    secret:
      name: pokedex-credentials # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: best-pokemon # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: remotely-created-secret-on-gcloud # Remote reference (where the secret is going to be pushed)